version: '3.8'

services:
  web:
    build: .
    container_name: aspnetcore_mvc_app
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=stationcontrol_db;user=root;password=root
    depends_on:
      - db

  db:
    image: mariadb:11.8
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationcontrol_db
      MYSQL_USER: stationcontrol_user
      MYSQL_PASSWORD: stationcontrol
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
